### ISSUE TITLE
Server.json problem

### ISSUE THREAD

**Issue by GreYzZ** [andrewda/CSGOItemDB.com#9]
Hello,
if I run the command server.json I get the error: 
module.js:341
    throw err;
    ^

Error: Cannot find module '/home/db/server.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3

How can I fix this?

**Comment by andrewda** [comment]
`server.json` does not exists. You need to run `server.js`.

That was my mistake on the README, it should be fixed now.
